#!/bin/bash

APPLICATION_FILE_PATH=xt
PRODUCT_HOME=/Library/__PRODUCT__/__VERSION__

echo "Post installation process started"

echo "Change permissions in product home"
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

rm -f /usr/local/bin/__PRODUCT__-__VERSION__
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__

rm -f /usr/local/bin/__PRODUCT__
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__

echo "Post installation process finished"
